export const formTabs = [
  {
    id: 1,
    title: "Application Information",
    fields: [
      { 
        key: "name", 
        label: "Name", 
        type: "text", 
        required: true 
      },
      { 
        key: "email", 
        label: "Email address", 
        type: "email", 
        required: true,
        validation: "email"
      },
      { 
        key: "city", 
        label: "City", 
        type: "text", 
        required: true 
      },
      { 
        key: "country", 
        label: "Country", 
        type: "select", 
        required: true 
      },
      { 
        key: "mobileNumber", 
        label: "Mobile number", 
        type: "text", 
        required: true,
        validation: "numbers"
      },
      { 
        key: "address", 
        label: "Address", 
        type: "text", 
        required: true 
      },
      { 
        key: "pin", 
        label: "Pin", 
        type: "text", 
        required: true,
        validation: "numbers"
      },
    ],
  },
  {
    id: 2,
    title: "Purpose and Documents",
    fields: [
      {
        key: "purpose",
        label: "Purpose",
        type: "select",
        required: true,
        options: ["Overfly", "Business", "Cargo", "Technical", "Medical", "Training"],
      },
      {
        key: "filedRoutePlan",
        label: "Filed Route Plan",
        type: "text",
        required: true,
        conditionalKey: "purpose",
        conditionalValue: "Overfly",
      },
      {
        key: "operatingCrewProfile",
        label: "Operating Crew Profile",
        type: "file",
        required: true,
        multiple: true,
      },
      {
        key: "travelerManifest",
        label: "Traveler Manifest",
        type: "file",
        required: true,
        multiple: true,
      },
      {
        key: "receivingContactReference",
        label: "Receiving Contact Reference",
        type: "file",
        required: true,
        multiple: true,
        conditionalKey: "purpose",
        conditionalValue: "Business",
      },
      {
        key: "authorizedSignatoryRecord",
        label: "Authorized Signatory Record",
        type: "file",
        required: true,
        conditionalKey: "purpose",
        conditionalValue: "Business",
      },
      {
        key: "connectingSectorConfirmation",
        label: "Connecting Sector Confirmation",
        type: "file",
        required: true,
      },
      {
        key: "groundHandlingConfirmation",
        label: "Ground Handling Confirmation",
        type: "text",
        required: true,
      },
      {
        key: "registrationDocumentCopy",
        label: "Registration Document Copy",
        type: "file",
        required: true,
      },
      {
        key: "medicalFitnessDocument",
        label: "Medical Fitness Document",
        type: "file",
        required: true,
        multiple: true,
      },
      {
        key: "consigneeAuthorizationNote",
        label: "Consignee Authorization Note",
        type: "file",
        required: true,
        multiple: true,
      },
      {
        key: "airworthinessComplianceRecord",
        label: "Airworthiness Compliance Record",
        type: "file",
        required: true,
        multiple: true,
      },
      {
        key: "airworthinessCertificates",
        label: "Airworthiness Certificates",
        type: "file",
        required: true,
        multiple: true,
      },
      {
        key: "operatorLicenseDetails",
        label: "Operator License Details",
        type: "file",
        required: true,
        multiple: true,
      },
      {
        key: "hullInsuranceDetails",
        label: "Hull Insurance Details",
        type: "file",
        required: true,
        multiple: true,
        conditionalKey: "purpose",
        conditionalValue: "Cargo",
      },
      {
        key: "acousticComplianceRecord",
        label: "Acoustic Compliance Record",
        type: "file",
        required: true,
        conditionalKey: "purpose",
        conditionalValue: "Cargo",
      },
      {
        key: "registrationEvidenceFile",
        label: "Registration Evidence File",
        type: "file",
        required: true,
      },
      {
        key: "waybillIdentifier",
        label: "Waybill Identifier",
        type: "file",
        required: true,
      },
      {
        key: "coverageCertificate",
        label: "Coverage Certificate",
        type: "file",
        required: true,
      },
      {
        key: "importClearancePermit",
        label: "Import Clearance Permit",
        type: "file",
        required: true,
      },
      {
        key: "hazardousCargoDeclaration",
        label: "Hazardous Cargo Declaration",
        type: "file",
        required: true,
      },
      {
        key: "technicalReleaseConfirmation",
        label: "Technical Release Confirmation",
        type: "text",
        required: true,
      },
      {
        key: "maintenanceConfirmation",
        label: "Maintenance Confirmation",
        type: "file",
        required: true,
      },
      {
        key: "crewExitLog",
        label: "Crew Exit Log",
        type: "file",
        required: true,
      },
      {
        key: "accommodationBookingProof",
        label: "Accommodation Booking Proof",
        type: "checkbox",
        required: false,
        conditionalKey: "crewDisembarkation",
        conditionalValue: true,
        conditionalLabel: "If Crew Disembarkation is checked",
        conditionalKey2: "purpose",
        conditionalValue2: "Technical",
      },
      {
        key: "hotelConfirmation",
        label: "If Yes please provide Hotel Confirmation",
        type: "file",
        required: true,
        conditionalKey: "purpose",
        conditionalValue: "Technical",
      },
      {
        key: "groundHandlingConfirmationTech",
        label: "Ground Handling Confirmation",
        type: "text",
        required: true,
        conditionalKey: "purpose",
        conditionalValue: "Technical",
      },
      {
        key: "medicalFacilityNote",
        label: "Medical Facility Note",
        type: "file",
        required: true,
        conditionalKey: "purpose",
        conditionalValue: "Medical",
      },
      {
        key: "passengerDetails",
        label: "Passenger Details",
        type: "file",
        required: true,
        conditionalKey: "purpose",
        conditionalValue: "Medical",
      },
      {
        key: "groundHandlingConfirmationMedical",
        label: "Ground Handling Confirmation",
        type: "text",
        required: true,
        conditionalKey: "purpose",
        conditionalValue: "Medical",
      },
      {
        key: "completeATSRoute",
        label: "Complete ATS Route",
        type: "text",
        required: true,
        conditionalKey: "purpose",
        conditionalValue: "Training",
      },
      {
        key: "circuitLandingCount",
        label: "Circuit Landing Count",
        type: "text",
        required: true,
        conditionalKey: "purpose",
        conditionalValue: "Training",
      },
      {
        key: "trainingSessionSchedule",
        label: "Training Session Schedule",
        type: "text",
        required: true,
        conditionalKey: "purpose",
        conditionalValue: "Training",
      },
      {
        key: "groundHandlingConfirmationTraining",
        label: "Ground Handling Confirmation",
        type: "text",
        required: false,
        conditionalKey: "purpose",
        conditionalValue: "Training",
      },
    ],
  },
  {
    id: 3,
    title: "Additional Information",
    fields: [
      { 
        key: "additionalDetails", 
        label: "Additional details", 
        type: "textarea", 
        required: false 
      },
      { 
        key: "additionalAttachment", 
        label: "Additional attachment", 
        type: "file", 
        required: false,
        multiple: true 
      },
      { 
        key: "agreement", 
        label: "Agreement", 
        type: "checkbox", 
        required: true 
      },
    ],
  },
  {
    id: 4,
    title: "Summary",
    summary: true,
    description: "Review all form data before submission",
    fields: [],
  },
];